# Generated by Django 6.0.4 on 2026-05-05 19:06

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations

SEARCH_VECTOR_SQL = """
CREATE FUNCTION notes_note_search_vector_update() RETURNS trigger AS $$
BEGIN
    NEW.search_vector :=
        setweight(to_tsvector('russian', coalesce(NEW.title, '')), 'A') ||
        setweight(to_tsvector('russian', coalesce(NEW.content, '')), 'B');
    RETURN NEW;
END
$$ LANGUAGE plpgsql;

UPDATE notes_note
SET search_vector =
    setweight(to_tsvector('russian', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('russian', coalesce(content, '')), 'B');

CREATE TRIGGER notes_note_search_vector_trigger
BEFORE INSERT OR UPDATE OF title, content ON notes_note
FOR EACH ROW EXECUTE FUNCTION notes_note_search_vector_update();
"""

DROP_SEARCH_VECTOR_SQL = """
DROP TRIGGER IF EXISTS notes_note_search_vector_trigger ON notes_note;
DROP FUNCTION IF EXISTS notes_note_search_vector_update();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_alter_note_title_comment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.RunSQL(
            sql=SEARCH_VECTOR_SQL,
            reverse_sql=DROP_SEARCH_VECTOR_SQL,
        ),
        migrations.AddIndex(
            model_name="note",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="note_search_vector_gin"
            ),
        ),
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name="note",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass("title", name="gin_trgm_ops"),
                name="note_title_trgm_gin",
            ),
        ),
    ]
