class DomainException(Exception): ...


class ValidationError(DomainException): ...


class UniqueConstraintError(DomainException): ...


class RepositoryError(Exception): ...


class ObjectNotFound(RepositoryError): ...


class AuthenticationError(Exception): ...
