# Generated by Django 6.0.4 on 2026-04-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_content_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='notes/%Y/%m', verbose_name='Картинка'),
        ),
    ]
